#!/usr/bin/env python3
"""Build the minimal BBK 9288 writable/executable RAM probe."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import build_9288  # noqa: E402


BUILD = ROOT / "build" / "exec-ram-probe"
PAYLOAD_SECTIONS = (
    (".probe_payload_a", "g_exec_ram_payload_a", "EXEC_RAM_PAYLOAD_A_SIZE"),
    (".probe_payload_b", "g_exec_ram_payload_b", "EXEC_RAM_PAYLOAD_B_SIZE"),
)


def run(command: list[str]) -> None:
    print("+", " ".join(command))
    subprocess.run(command, check=True)


def capture(command: list[str]) -> str:
    print("+", " ".join(command))
    return subprocess.check_output(command, text=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sdk", type=Path, required=True)
    parser.add_argument("--toolchain", type=Path, required=True)
    parser.add_argument(
        "--output", type=Path, default=BUILD / "EXEC_RAM.exe"
    )
    return parser.parse_args()


def write_payload_header(payloads: list[tuple[str, str, bytes]], path: Path) -> None:
    lines = [
        "/* Generated by build_9288_exec_ram_probe.py. */",
        "#ifndef EXEC_RAM_PAYLOADS_H",
        "#define EXEC_RAM_PAYLOADS_H",
        "",
    ]
    for symbol, size_macro, data in payloads:
        lines.append(f"#define {size_macro} {len(data)}u")
        lines.append(f"static const u8 {symbol}[{size_macro}] = {{")
        for offset in range(0, len(data), 12):
            chunk = data[offset:offset + 12]
            lines.append("    " + ", ".join(f"0x{byte:02x}u" for byte in chunk) + ",")
        lines.extend(("};", ""))
    lines.extend(("#endif", ""))
    path.write_text("\n".join(lines), encoding="ascii")


def main() -> None:
    args = parse_args()
    BUILD.mkdir(parents=True, exist_ok=True)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    include = BUILD / "sdk-include"
    generated = BUILD / "generated"
    generated.mkdir(parents=True, exist_ok=True)
    build_9288.prepare_sdk_headers(args.sdk.resolve(), include)
    toolchain = args.toolchain.resolve()
    clang = build_9288.find_tool(toolchain, "clang")
    objcopy = build_9288.find_tool(toolchain, "llvm-objcopy")
    readelf = build_9288.find_tool(toolchain, "llvm-readelf")
    common_flags = [
        "--target=s1c33-none-elf",
        "-O2",
        "-ffreestanding",
        "-fno-builtin",
        "-fno-unwind-tables",
        "-fno-asynchronous-unwind-tables",
        "-fomit-frame-pointer",
        "-fdata-sections",
        "-ffunction-sections",
        "-Wall",
        "-Wextra",
        "-Werror",
        "-Wno-pointer-to-int-cast",
        "-Wno-int-to-pointer-cast",
        "-DDL_DOWN",
        "-D_RLS_",
        "-I",
        str(ROOT / "src" / "9288_compat"),
        "-I",
        str(include),
        "-I",
        str(ROOT / "src"),
    ]

    payload_object = BUILD / "9288_exec_ram_payload.o"
    run([
        clang, *common_flags, "-c",
        str(ROOT / "tests" / "9288_exec_ram_payload.c"),
        "-o", str(payload_object),
    ])
    relocations = capture([readelf, "-r", str(payload_object)])
    if "There are no relocations" not in relocations:
        raise SystemExit(
            "generated payload is not position independent:\n" + relocations
        )

    payloads: list[tuple[str, str, bytes]] = []
    for section, symbol, size_macro in PAYLOAD_SECTIONS:
        raw = BUILD / f"{section[1:]}.bin"
        run([
            objcopy, "-O", "binary", f"--only-section={section}",
            str(payload_object), str(raw),
        ])
        data = raw.read_bytes()
        if not data or len(data) > 128:
            raise SystemExit(f"unexpected {section} size: {len(data)}")
        payloads.append((symbol, size_macro, data))
    if payloads[0][2] == payloads[1][2]:
        raise SystemExit("the two overwrite-test payloads are identical")
    header = generated / "9288_exec_ram_payloads.h"
    write_payload_header(payloads, header)

    sources = [
        ROOT / "src" / "gam4980_9288_start.c",
        ROOT / "src" / "gam4980_9288_runtime.c",
        ROOT / "tests" / "9288_exec_ram_probe.c",
    ]
    objects: list[Path] = []
    for source in sources:
        output = BUILD / f"{source.stem}.o"
        run([
            clang, *common_flags, "-I", str(generated),
            "-c", str(source), "-o", str(output),
        ])
        objects.append(output)

    elf = BUILD / "EXEC_RAM.elf"
    map_path = BUILD / "EXEC_RAM.map"
    run([
        clang,
        "--target=s1c33-none-elf",
        "-fuse-ld=lld",
        "-nostdlib",
        "-Wl,--gc-sections",
        f"-Wl,-T,{ROOT / 'src' / 'gam4980_9288.ld'}",
        f"-Wl,-Map,{map_path}",
        *(str(item) for item in objects),
        "-o", str(elf),
    ])
    raw = BUILD / "EXEC_RAM.bin"
    run([objcopy, "-O", "binary", "--gap-fill", "255", str(elf), str(raw)])
    payload = raw.read_bytes()
    payload_end = build_9288.read_map_symbol(map_path, "__payload_end")
    expected = payload_end - build_9288.APP_LOAD_ADDRESS
    if len(payload) != expected:
        raise SystemExit(f"payload size {len(payload)} != expected {expected}")

    app = bytearray(build_9288.pack_kf2(payload))
    app[12:28] = b"EXEC_RAM".ljust(16, b"\0")
    args.output.write_bytes(app)
    print(f"payload A: {len(payloads[0][2])} bytes, {payloads[0][2].hex()}")
    print(f"payload B: {len(payloads[1][2])} bytes, {payloads[1][2].hex()}")
    print(f"built: {args.output.resolve()}")
    print(f"size: {len(app)}")
    print(f"sha256: {hashlib.sha256(app).hexdigest()}")


if __name__ == "__main__":
    main()
