"""Derive map-proven glyph kernels, retaining the audited return-state logic."""
from pathlib import Path
import argparse
from generate_native_graphics import extract

ROOT=Path(__file__).resolve().parents[1]
def generate():
    original=(ROOT/'src/firmware_native_text.c').read_text(encoding='utf-8')
    parts=['/* Generated by tools/generate_native_text_flat.py; do not edit. */']
    for name in ('fnt_ascii_row','fnt_chinese_row'):
        args,body=extract(original,name)
        args=args.replace('s6502_iram_asm_context_t *c','fnt_flat_env *f')
        body=body.replace('fnt_read(c,','ft_read(f,').replace('fnt_write(c,','ft_write(f,')
        body=body.replace('fnt_cursor(c,','ft_cursor(f,')
        body=body.replace('{','{\n    s6502_iram_asm_context_t *c=f->c;',1)
        parts.append('FNT_INLINE void '+name.replace('fnt_','ft_')+'('+args+')'+body)
    return '\n\n'.join(parts)+'\n'
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args()
    target=ROOT/'src/firmware_native_text_flat_generated.h';data=generate()
    if a.check:
        assert target.read_text(encoding='utf-8')==data,'regenerate native text kernels'
    else:target.write_text(data,encoding='utf-8')
