"""Extract the already-tested firmware graphics algorithms into PIC NAT code.

This is source migration, not a guest interpreter or an EXE trampoline.  The
generated header is checked in; --check verifies it still matches the audited
core implementations. Only explicit names are copied, with context-local
memory services replacing the original global emulator dependencies.
"""
from pathlib import Path
import argparse
import re

ROOT = Path(__file__).resolve().parents[1]
FUNCTIONS = [
    ('nz', 'uint8_t'), ('adc8', 'uint8_t'), ('sbc8', 'uint8_t'),
    ('indirect_y_cycles', 'uint32_t'), ('zp16', 'uint16_t'),
    ('shift_pair', 'uint16_t'), ('shift_cost', 'uint32_t'),
    ('shift_first_cost', 'uint32_t'), ('shift_destination_cost', 'uint32_t'),
    ('shift_masked_destination_cost', 'uint32_t'),
    ('shift_low_tail_destination_cost', 'uint32_t'),
    ('address_update_cycles', 'uint32_t'), ('region_write_safe', 'int'),
    ('add_high_overflow', 'uint8_t'), ('sub_high_overflow', 'uint8_t'),
    ('shift_row_cycles', 'uint32_t'), ('shift_prefix', 'int'),
    ('shift_region', 'int'), ('picture_tail', 'int'),
    ('bitmap_row_cycles', 'uint32_t'), ('bitmap_region', 'int'),
    ('graphics_address', 'int'), ('hline_middle', 'int'),
    ('part_picture_row', 'int'), ('pixel_tail', 'int'),
    ('picture_head', 'int'), ('picture_resume', 'int'),
]


def extract(source, name):
    masked = re.sub(r'/\*.*?\*/|//[^\n]*|"(?:\\.|[^"\\])*"',
                    lambda m: ' ' * len(m[0]), source, flags=re.S)
    matches = list(re.finditer(r'\b' + re.escape(name) +
                              r'\s*\(([^;{}]*)\)\s*\{', masked))
    if len(matches) != 1:
        raise ValueError(f'{name}: expected exactly one definition')
    m = matches[0]
    opening = m.end() - 1
    depth = 1
    closing = opening + 1
    while depth:
        depth += (masked[closing] == '{') - (masked[closing] == '}')
        closing += 1
    return source[m.start(1):m.end(1)], source[opening:closing]


def generate():
    source = (ROOT / 'src/gam4980_core.c').read_text(encoding='utf-8')
    result = ['/* Generated by tools/generate_native_graphics.py; do not edit. */',
              '#ifndef FIRMWARE_NATIVE_GRAPHICS_ALGORITHMS_H',
              '#define FIRMWARE_NATIVE_GRAPHICS_ALGORITHMS_H', '']
    for short, returns in FUNCTIONS:
        args, body = extract(source, 's6502_firmware_hle_' + short)
        if short == 'shift_prefix':
            # This prepares the EXE's optional subsequent inner-loop pointer
            # cache. It has no guest architectural effect and must not create
            # a hidden dependency or global state in a pageable NAT module.
            start = body.index('    s6502_hle_shift_cache.valid = 0u;')
            end = body.index('    ram[0x20e7u] = 3u;', start)
            body = body[:start] + ('    if (consumed > cycle_budget)\n'
                                   '        return 0;\n\n') + body[end:]
        if short in ('shift_region', 'bitmap_region'):
            args = re.sub(r',\s*s6502_hle_\w+_fn\s+\w+', '', args)
            body = body.replace('row_cycles_function(',
                's6502_firmware_hle_' +
                ('shift_row_cycles(' if short == 'shift_region' else 'bitmap_row_cycles('))
            body = body.replace('prefix_function(', 's6502_firmware_hle_shift_prefix(')
        body = body.replace('s6502_stack_ram', 'fg->ram')
        body = body.replace('s6502_page3', 'fg->page3')
        body = body.replace('sys_halt_p()', '(fg->ram[0x200u] & 8u)')
        body = re.sub(r'\bmem_read\s*\(', 'fg_read(fg, ', body)
        body = re.sub(r'\bmem_write\s*\(', 'fg_write(fg, ', body)
        for dependency, _ in FUNCTIONS:
            body = re.sub(r'\bs6502_firmware_hle_' + dependency + r'\s*\(',
                          'fg_alg_' + dependency + '(fg, ', body)
        args = args.replace('s6502_hle_direct_result_t', 'fg_direct_result_t')
        args = args.replace('s6502_hle_region_result_t', 'fg_region_result_t')
        if re.search(r'\bs6502_|\bsys\.|\bmem_(?:read|write)\b', body):
            raise ValueError(f'{short}: unbound dependency remains')
        result.extend([f'FG_INLINE {returns} fg_alg_{short}(fg_env_t *fg, {args.strip()})',
                       body, ''])
    result.extend(['#endif', ''])
    return '\n'.join(result)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = ROOT / 'src/firmware_native_graphics_algorithms.h'
    output = generate()
    if args.check:
        if path.read_text(encoding='utf-8') != output:
            raise SystemExit('generated graphics algorithms are stale')
    else:
        path.write_text(output, encoding='utf-8')
    print(f'firmware graphics: {len(FUNCTIONS)} context-local algorithms verified')
