/* Generated by tools/generate_native_text_flat.py; do not edit. */

FNT_INLINE void ft_ascii_row(fnt_flat_env *f,
    uint32_t ix, uint32_t sp, uint32_t status,
    firmware_native_text_result_t *result){
    s6502_iram_asm_context_t *c=f->c;
    const firmware_native_graphics_services_t *g =
        (const firmware_native_graphics_services_t *)(FNT_POINTER)c->graphics;
    const uint8_t *page3 = (const uint8_t *)(FNT_POINTER)g->page3;
    uint8_t *ram = ((uint8_t *)(FNT_POINTER)c->ram);
    uint32_t source_index = ix & 0xffu;
    uint32_t stack_pointer = sp & 0xffu;
    uint32_t status_value = status & 0xffu;
    uint32_t source;
    uint32_t destination;
    uint32_t alternate;
    uint32_t value;
    uint32_t bits;
    uint32_t column;
    uint32_t row;
    uint32_t return_address;
    uint32_t carry;

    /*
     * Keep the complete HLE row outside s6502_exec().  The S1C33 backend can
     * otherwise reuse dirty upper bits of its byte-sized CPU-register locals
     * across the many indirect memory calls in this block.  Full-width values
     * with explicit masks make each 6502 wrap point unambiguous.
     */
    source = (uint32_t)ram[0x2fu] | ((uint32_t)ram[0x30u] << 8);
    value = (uint32_t)ft_read(f, (uint16_t)((source + source_index) & 0xffffu));
    bits = fnt_glyph_bits(
        value & 0xffu, (uint32_t)ft_read(f, 0x208bu) & 7u
    );
    ft_write(f, 0x20b3u, (uint8_t)bits);
    ft_write(f, 0x20b4u, (uint8_t)(bits >> 8));
    ft_write(f, 0x20e5u, (uint8_t)(bits >> 16));
    ft_write(f, 0x20e6u, (uint8_t)(bits >> 24));

    column = (uint32_t)ft_read(f, 0x2081u) & 0xffu;
    destination = (uint32_t)ram[0x3au] | ((uint32_t)ram[0x3bu] << 8);
    if (column == 0x98u) {
        result->iy = 0u;
        value = (uint32_t)ft_read(f, 0x20b3u) & 0xfeu;
        ft_write(f, 0x20e6u, (uint8_t)value);
        value = ((uint32_t)ft_read(f, (uint16_t)destination) & 0x01u) | value;
        ft_write(f, (uint16_t)destination, (uint8_t)value);
        return_address = 0x663du;
    } else if (column >= 8u) {
        result->iy = 1u;
        alternate = (uint32_t)page3[0xe6u] |
                    ((uint32_t)page3[0xe7u] << 8);
        if (page3[0xe5u] == 1u && destination == alternate) {
            alternate = (uint32_t)page3[0xe8u] |
                        ((uint32_t)page3[0xe9u] << 8);
            value = ((uint32_t)ft_read(f, (uint16_t)alternate) &
                     (uint32_t)ft_read(f, 0x20e5u)) |
                    (uint32_t)ft_read(f, 0x20b3u);
            ft_write(f, (uint16_t)alternate, (uint8_t)value);
            return_address = 0x6598u;
        } else {
            value = ((uint32_t)ft_read(f, (uint16_t)destination) &
                     (uint32_t)ft_read(f, 0x20e5u)) |
                    (uint32_t)ft_read(f, 0x20b3u);
            ft_write(f, (uint16_t)destination, (uint8_t)value);
            return_address = 0x65b9u;
        }
        value = ((uint32_t)ft_read(f,
                     (uint16_t)((destination + 1u) & 0xffffu)) &
                 (uint32_t)ft_read(f, 0x20e6u)) |
                (uint32_t)ft_read(f, 0x20b4u);
        ft_write(f,
            (uint16_t)((destination + 1u) & 0xffffu), (uint8_t)value
        );
    } else {
        result->iy = 0u;
        alternate = (uint32_t)ram[0x38u] | ((uint32_t)ram[0x39u] << 8);
        value = ((uint32_t)ft_read(f, (uint16_t)alternate) &
                 (uint32_t)ft_read(f, 0x20e5u)) |
                (uint32_t)ft_read(f, 0x20b3u);
        ft_write(f, (uint16_t)alternate, (uint8_t)value);

        alternate = (uint32_t)page3[0xe6u] |
                    ((uint32_t)page3[0xe7u] << 8);
        if (page3[0xe5u] == 1u && destination == alternate) {
            alternate = (uint32_t)page3[0xe8u] |
                        ((uint32_t)page3[0xe9u] << 8);
            value = ((uint32_t)ft_read(f, (uint16_t)alternate) &
                     (uint32_t)ft_read(f, 0x20e6u)) |
                    (uint32_t)ft_read(f, 0x20b4u);
            ft_write(f, (uint16_t)alternate, (uint8_t)value);
            return_address = 0x660au;
        } else {
            value = ((uint32_t)ft_read(f, (uint16_t)destination) &
                     (uint32_t)ft_read(f, 0x20e6u)) |
                    (uint32_t)ft_read(f, 0x20b4u);
            ft_write(f, (uint16_t)destination, (uint8_t)value);
            return_address = 0x6620u;
        }
    }

    /* Preserve the two stack bytes written by the inlined JSR. */
    ram[0x100u | stack_pointer] = (uint8_t)(return_address >> 8);
    ram[0x100u | ((stack_pointer - 1u) & 0xffu)] =
        (uint8_t)return_address;

    ft_cursor(f, ram, status_value, &value, &status_value);
    source_index = (source_index + 1u) & 0xffu;
    status_value = (status_value & ~0x82u) | (source_index & 0x80u) |
                   (source_index ? 0u : 0x02u);

    result->ac = (uint8_t)value;
    result->ix = (uint8_t)source_index;
    result->status = (uint8_t)status_value;
}

FNT_INLINE void ft_chinese_row(fnt_flat_env *f,
    uint32_t ix, uint32_t sp, uint32_t status,
    firmware_native_text_result_t *result){
    s6502_iram_asm_context_t *c=f->c;
    const firmware_native_graphics_services_t *g =
        (const firmware_native_graphics_services_t *)(FNT_POINTER)c->graphics;
    const uint8_t *page3 = (const uint8_t *)(FNT_POINTER)g->page3;
    uint8_t *ram = ((uint8_t *)(FNT_POINTER)c->ram);
    uint32_t source_index = ix & 0xffu;
    uint32_t stack_pointer = sp & 0xffu;
    uint32_t status_value = status & 0xffu;
    uint32_t source;
    uint32_t destination;
    uint32_t alternate;
    uint32_t raw;
    uint32_t bits;
    uint32_t value;
    uint32_t b3;
    uint32_t b4;
    uint32_t b5;
    uint32_t left_mask;
    uint32_t right_mask;
    uint32_t shift;
    uint32_t column;
    uint32_t row;
    uint32_t return_address;
    uint32_t carry;

    source = (uint32_t)ram[0x2fu] | ((uint32_t)ram[0x30u] << 8);
    b3 = (uint32_t)ft_read(f,
        (uint16_t)((source + source_index) & 0xffffu)
    );
    b4 = (uint32_t)ft_read(f,
        (uint16_t)((source + source_index + 1u) & 0xffffu)
    );
    raw = ((b3 & 0xffu) << 16) | ((b4 & 0xffu) << 8);
    shift = (uint32_t)ft_read(f, 0x208bu) & 7u;
    switch (shift) {
    default:
    case 0u:
        bits = raw;
        left_mask = 0u;
        right_mask = 0xffu;
        break;
    case 1u:
        bits = raw >> 1;
        left_mask = 0x80u;
        right_mask = 0x7fu;
        break;
    case 2u:
        bits = raw >> 2;
        left_mask = 0xc0u;
        right_mask = 0x3fu;
        break;
    case 3u:
        bits = raw >> 3;
        left_mask = 0xe0u;
        right_mask = 0x1fu;
        break;
    case 4u:
        bits = raw >> 4;
        left_mask = 0xf0u;
        right_mask = 0x0fu;
        break;
    case 5u:
        bits = raw >> 5;
        left_mask = 0xf8u;
        right_mask = 0x07u;
        break;
    case 6u:
        bits = raw >> 6;
        left_mask = 0xfcu;
        right_mask = 0x03u;
        break;
    case 7u:
        bits = raw >> 7;
        left_mask = 0xfeu;
        right_mask = 0x01u;
        break;
    }
    b3 = (bits >> 16) & 0xffu;
    b4 = (bits >> 8) & 0xffu;
    b5 = bits & 0xffu;
    ft_write(f, 0x20b3u, (uint8_t)b3);
    ft_write(f, 0x20b4u, (uint8_t)b4);
    ft_write(f, 0x20b5u, (uint8_t)b5);
    ft_write(f, 0x20e5u, (uint8_t)left_mask);
    ft_write(f, 0x20e6u, (uint8_t)right_mask);

    column = (uint32_t)ft_read(f, 0x2081u) & 0xffu;
    destination = (uint32_t)ram[0x3au] | ((uint32_t)ram[0x3bu] << 8);
    if (column == 0x90u) {
        result->iy = 0u;
        value = ((uint32_t)ft_read(f, (uint16_t)destination) & left_mask) | b3;
        ft_write(f, (uint16_t)destination, (uint8_t)value);
        result->iy = 1u;
        right_mask = b4 & 0xfeu;
        ft_write(f, 0x20e6u, (uint8_t)right_mask);
        value = ((uint32_t)ft_read(f,
                     (uint16_t)((destination + 1u) & 0xffffu)) & 0x01u) |
                right_mask;
        ft_write(f,
            (uint16_t)((destination + 1u) & 0xffffu), (uint8_t)value
        );
        return_address = 0x61bbu;
    } else if (column >= 8u) {
        result->iy = 0u;
        alternate = (uint32_t)page3[0xe6u] |
                    ((uint32_t)page3[0xe7u] << 8);
        if (page3[0xe5u] == 1u && destination == alternate) {
            alternate = (uint32_t)page3[0xe8u] |
                        ((uint32_t)page3[0xe9u] << 8);
            value = ((uint32_t)ft_read(f, (uint16_t)alternate) & left_mask) |
                    b3;
            ft_write(f, (uint16_t)alternate, (uint8_t)value);
        } else {
            value = ((uint32_t)ft_read(f, (uint16_t)destination) & left_mask) |
                    b3;
            ft_write(f, (uint16_t)destination, (uint8_t)value);
        }
        ft_write(f,
            (uint16_t)((destination + 1u) & 0xffffu), (uint8_t)b4
        );
        value = ((uint32_t)ft_read(f,
                     (uint16_t)((destination + 2u) & 0xffffu)) & right_mask) |
                b5;
        ft_write(f,
            (uint16_t)((destination + 2u) & 0xffffu), (uint8_t)value
        );
        result->iy = 2u;
        return_address = 0x6130u;
    } else {
        result->iy = 0u;
        alternate = (uint32_t)ram[0x38u] | ((uint32_t)ram[0x39u] << 8);
        value = ((uint32_t)ft_read(f, (uint16_t)alternate) & left_mask) | b3;
        ft_write(f, (uint16_t)alternate, (uint8_t)value);

        alternate = (uint32_t)page3[0xe6u] |
                    ((uint32_t)page3[0xe7u] << 8);
        if (page3[0xe5u] == 1u && destination == alternate) {
            alternate = (uint32_t)page3[0xe8u] |
                        ((uint32_t)page3[0xe9u] << 8);
            ft_write(f, (uint16_t)alternate, (uint8_t)b4);
        } else {
            ft_write(f, (uint16_t)destination, (uint8_t)b4);
        }
        value = ((uint32_t)ft_read(f,
                     (uint16_t)((destination + 1u) & 0xffffu)) & right_mask) |
                b5;
        ft_write(f,
            (uint16_t)((destination + 1u) & 0xffffu), (uint8_t)value
        );
        result->iy = 1u;
        return_address = 0x6192u;
    }

    ram[0x100u | stack_pointer] = (uint8_t)(return_address >> 8);
    ram[0x100u | ((stack_pointer - 1u) & 0xffu)] =
        (uint8_t)return_address;

    /* Inline the shared $6646 address-update helper exactly as the regular
     * glyph-row HLE does. */
    ft_cursor(f, ram, status_value, &value, &status_value);
    source_index = (source_index + 2u) & 0xffu;
    status_value = (status_value & ~0x82u) | (source_index & 0x80u) |
                   (source_index ? 0u : 0x02u);

    result->ac = (uint8_t)value;
    result->ix = (uint8_t)source_index;
    result->status = (uint8_t)status_value;
}
