/* Generated by tools/generate_native_graphics.py; do not edit. */
#ifndef FIRMWARE_NATIVE_GRAPHICS_ALGORITHMS_H
#define FIRMWARE_NATIVE_GRAPHICS_ALGORITHMS_H

FG_INLINE uint8_t fg_alg_nz(fg_env_t *fg, uint8_t status, uint8_t value)
{
    return (uint8_t)((status & ~0x82u) | (value & 0x80u) |
        (value ? 0u : 0x02u));
}

FG_INLINE uint8_t fg_alg_adc8(fg_env_t *fg, uint8_t status, uint8_t left, uint8_t right, uint8_t *value)
{
    uint16_t sum = (uint16_t)left + right + (status & 1u);
    uint8_t result = (uint8_t)sum;

    status = fg_alg_nz(fg, status, result);
    status = (uint8_t)((status & ~0x41u) | (sum > 0xffu) |
        ((~(left ^ right) & (left ^ result) & 0x80u) ? 0x40u : 0u));
    *value = result;
    return status;
}

FG_INLINE uint8_t fg_alg_sbc8(fg_env_t *fg, uint8_t status, uint8_t left, uint8_t right, uint8_t *value)
{
    uint16_t difference = (uint16_t)left - right -
        ((status & 1u) ? 0u : 1u);
    uint8_t result = (uint8_t)difference;

    status = fg_alg_nz(fg, status, result);
    status = (uint8_t)((status & ~0x41u) |
        (difference < 0x100u ? 1u : 0u) |
        (((left ^ result) & (left ^ right) & 0x80u) ? 0x40u : 0u));
    *value = result;
    return status;
}

FG_INLINE uint32_t fg_alg_indirect_y_cycles(fg_env_t *fg, uint8_t pointer_low, uint8_t y)
{
    return 5u + ((uint32_t)pointer_low + y > 0xffu);
}

FG_INLINE uint16_t fg_alg_zp16(fg_env_t *fg, const uint8_t *ram, uint32_t low)
{
    return (uint16_t)(ram[low] | ((uint16_t)ram[low + 1u] << 8));
}

FG_INLINE uint16_t fg_alg_shift_pair(fg_env_t *fg, uint8_t high, uint8_t low, uint8_t shift)
{
    uint16_t pair = (uint16_t)(((uint16_t)high << 8) | low);

    return shift < 16u ? (uint16_t)(pair >> shift) : 0u;
}

FG_INLINE uint32_t fg_alg_shift_cost(fg_env_t *fg, uint32_t shift)
{
    return shift ? 53u + 19u * shift : 55u;
}

FG_INLINE uint32_t fg_alg_shift_first_cost(fg_env_t *fg, uint32_t shift)
{
    return shift ? 26u + 19u * shift : 28u;
}

FG_INLINE uint32_t fg_alg_shift_destination_cost(fg_env_t *fg, uint16_t address)
{
    if (address == 0x0400u)
        return 75u;
    return (address >> 8) == 0x04u ? 41u : 31u;
}

FG_INLINE uint32_t fg_alg_shift_masked_destination_cost(fg_env_t *fg, uint16_t address)
{
    if (address == 0x0400u)
        return 87u;
    return (address >> 8) == 0x04u ? 53u : 43u;
}

FG_INLINE uint32_t fg_alg_shift_low_tail_destination_cost(fg_env_t *fg, uint16_t address)
{
    if (address == 0x0400u)
        return 84u;
    return (address >> 8) == 0x04u ? 51u : 41u;
}

FG_INLINE uint32_t fg_alg_address_update_cycles(fg_env_t *fg, uint8_t row, uint8_t column)
{
    if (row < 0x40u)
        return 59u;
    if (row == 0x40u)
        return 51u;
    if (row != 0x41u)
        return 67u;
    if (column < 8u)
        return 53u;
    return 76u + 40u * ((column - 8u) >> 3);
}

FG_INLINE int fg_alg_region_write_safe(fg_env_t *fg, uint16_t address, uint32_t size)
{
    uint32_t end = (uint32_t)address + size;

    return size && end <= 0x10000u && address >= 0x0300u &&
        !(address < 0x2100u && end > 0x2000u);
}

FG_INLINE uint8_t fg_alg_add_high_overflow(fg_env_t *fg, uint8_t value, uint8_t result)
{
    return (uint8_t)(
        ((uint8_t)~value & (uint8_t)(value ^ result) & 0x80u) != 0u
    );
}

FG_INLINE uint8_t fg_alg_sub_high_overflow(fg_env_t *fg, uint8_t value, uint8_t result)
{
    return (uint8_t)(((value ^ result) & value & 0x80u) != 0u);
}

FG_INLINE uint32_t fg_alg_shift_row_cycles(fg_env_t *fg, const uint8_t *ram)
{
    uint32_t width = ram[0x20e8u];
    uint32_t shift = ram[0x20cfu];
    uint32_t cycles;
    uint32_t remaining;
    uint16_t source = fg_alg_zp16(fg, ram, 0x2fu);
    uint16_t first_destination = fg_alg_zp16(fg, ram, 0x38u);
    uint16_t destination = fg_alg_zp16(fg, ram, 0x3au);
    uint8_t row = ram[0x2082u];
    uint8_t column = ram[0x2081u];

    if (!width || !ram[0x20dau] || shift > 7u ||
        source < 0x0300u || (uint32_t)source + width + 1u > 0x10000u ||
        !fg_alg_region_write_safe(fg, first_destination, 1u) ||
        !fg_alg_region_write_safe(fg, destination, width) ||
        fg->page3[0xe5u] != 1u || fg->page3[0xe6u] != 0u ||
        fg->page3[0xe7u] != 4u || fg->page3[0xe8u] != 0u ||
        fg->page3[0xe9u] != 0x10u)
        return 0u;

    cycles = 23u + fg_alg_shift_first_cost(fg, shift) +
        (width > 1u ? 39u : 38u);
    remaining = width - 1u;
    if (remaining) {
        uint32_t end = (uint32_t)destination + remaining;
        uint32_t first_special = destination > 0x400u ? destination : 0x400u;
        uint32_t last_special = end < 0x500u ? end : 0x500u;
        cycles += remaining * (fg_alg_shift_cost(fg, shift) + 70u) - 2u;
        if (last_special > first_special) cycles += 10u * (last_special - first_special);
        if (destination <= 0x400u && end > 0x400u) cycles += 34u;
        destination = (uint16_t)end;
    }

    if ((ram[0x2083u] & 7u) >= (column & 7u)) {
        cycles += 23u + fg_alg_shift_cost(fg, shift) + 14u;
        cycles +=
            fg_alg_shift_masked_destination_cost(fg, destination);
    } else {
        cycles += 25u + fg_alg_shift_first_cost(fg, shift) + 14u;
        cycles +=
            fg_alg_shift_low_tail_destination_cost(fg, destination);
    }
    cycles += fg_alg_address_update_cycles(fg, row, column);
    cycles += ram[0x20dau] == 1u ? 100u : 96u;
    return cycles;
}

FG_INLINE int fg_alg_shift_prefix(fg_env_t *fg, uint32_t sp, uint32_t status, uint32_t cycle_budget,
    fg_region_result_t *result)
{
    uint8_t *ram = fg->ram;
    uint32_t width = ram[0x20e8u];
    uint32_t shift = ram[0x20cfu];
    uint32_t consumed = 23u + fg_alg_shift_first_cost(fg, shift) +
        (width > 1u ? 39u : 38u);
    uint32_t remaining = width - 1u;
    uint32_t status_value = status & 0xffu;
    uint32_t value;
    uint16_t source = fg_alg_zp16(fg, ram, 0x2fu);
    uint16_t first_destination = fg_alg_zp16(fg, ram, 0x38u);
    uint16_t destination = fg_alg_zp16(fg, ram, 0x3au);
    uint16_t target;
    uint16_t pair;
    uint8_t high;
    uint8_t high_result;

    if (consumed > cycle_budget)
        return 0;

    ram[0x20e7u] = 3u;
    ram[0x20d8u] = (uint8_t)width;
    ram[0x20e6u] = fg_read(fg, source);
    ram[0x20e5u] = 0u;
    pair = fg_alg_shift_pair(fg, 0u, ram[0x20e6u], (uint8_t)shift);
    ram[0x20e5u] = (uint8_t)(pair >> 8);
    ram[0x20e6u] = (uint8_t)pair;
    value = (uint32_t)fg_read(fg, first_destination) & ram[0x20e3u];
    value |= ram[0x20e6u];
    fg_write(fg, first_destination, (uint8_t)value);
    ram[0x20d8u] = (uint8_t)remaining;

    for (;;) {
        uint32_t after;
        uint32_t iteration_cycles;

        if (!remaining)
            break;
        after = remaining - 1u;
        iteration_cycles = fg_alg_shift_cost(fg, shift) +
            fg_alg_shift_destination_cost(fg, destination) +
            (after ? 39u : 37u);
        if (iteration_cycles > cycle_budget - consumed)
            break;

        consumed += iteration_cycles;
        ram[0x20e5u] = fg_read(fg, source);
        source = (uint16_t)(source + 1u);
        ram[0x2fu] = (uint8_t)source;
        ram[0x30u] = (uint8_t)(source >> 8);
        ram[0x20e6u] = fg_read(fg, source);
        pair = fg_alg_shift_pair(fg,
            ram[0x20e5u], ram[0x20e6u], (uint8_t)shift
        );
        ram[0x20e5u] = (uint8_t)(pair >> 8);
        ram[0x20e6u] = (uint8_t)pair;
        target = destination == 0x0400u ? 0x1000u : destination;
        fg_write(fg, target, ram[0x20e6u]);

        high = (uint8_t)(destination >> 8);
        destination = (uint16_t)(destination + 1u);
        high_result = (uint8_t)(destination >> 8);
        status_value &= ~0x40u;
        if (fg_alg_add_high_overflow(fg, high, high_result))
            status_value |= 0x40u;
        ram[0x3au] = (uint8_t)destination;
        ram[0x3bu] = (uint8_t)(destination >> 8);

        remaining = after;
        ram[0x20d8u] = (uint8_t)remaining;
    }

    status_value &= ~0x83u;
    status_value |= 0x01u | ((uint8_t)remaining & 0x80u) |
        (remaining ? 0u : 0x02u);
    result->cycles = consumed;
    result->rows = 1u;
    result->pc = remaining ? 0x6a75u : 0x6b05u;
    result->ac = (uint8_t)remaining;
    result->ix = 0u;
    result->iy = 0u;
    result->sp = (uint8_t)sp;
    result->status = (uint8_t)status_value;
    return 1;
}

FG_INLINE int fg_alg_shift_region(fg_env_t *fg, uint32_t sp, uint32_t status, uint32_t cycle_budget,
    fg_region_result_t *result)
{
    uint8_t *ram = fg->ram;
    uint32_t cycles = 0u;
    uint32_t rows = 0u;
    uint32_t status_value = status & 0xffu;
    uint16_t return_pc = 0x6988u;
    uint8_t stack_pointer = (uint8_t)sp;
    int failure = 0;

    for (;;) {
        uint32_t row_cycles = fg_alg_shift_row_cycles(fg, ram);
        uint32_t width;
        uint32_t remaining;
        uint32_t value;
        uint32_t sum;
        uint16_t source;
        uint16_t first_destination;
        uint16_t destination;
        uint16_t target;
        uint16_t pair;
        uint8_t shift;
        uint8_t row;
        uint8_t column;
        uint8_t low;
        uint8_t high;
        uint8_t carry;
        uint8_t high_result;
        uint8_t overflow;

        if (!row_cycles) {
            failure = -1;
            break;
        }
        if (row_cycles > cycle_budget - cycles) {
            if (!rows)
                return fg_alg_shift_prefix(fg,
                    sp, status, cycle_budget, result
                );
            failure = 0;
            break;
        }

        ++rows;
        cycles += row_cycles;
        width = ram[0x20e8u];
        shift = ram[0x20cfu];
        source = fg_alg_zp16(fg, ram, 0x2fu);
        first_destination = fg_alg_zp16(fg, ram, 0x38u);
        destination = fg_alg_zp16(fg, ram, 0x3au);
        row = ram[0x2082u];
        column = ram[0x2081u];

        ram[0x20e7u] = 3u;
        ram[0x20d8u] = (uint8_t)width;
        ram[0x20e6u] = fg_read(fg, source);
        ram[0x20e5u] = 0u;
        pair = fg_alg_shift_pair(fg, 0u, ram[0x20e6u], shift);
        ram[0x20e5u] = (uint8_t)(pair >> 8);
        ram[0x20e6u] = (uint8_t)pair;
        value = (uint32_t)fg_read(fg, first_destination) & ram[0x20e3u];
        value |= ram[0x20e6u];
        fg_write(fg, first_destination, (uint8_t)value);
        remaining = width - 1u;
        ram[0x20d8u] = (uint8_t)remaining;

        while (remaining) {
            ram[0x20e5u] = fg_read(fg, source);
            source = (uint16_t)(source + 1u);
            ram[0x2fu] = (uint8_t)source;
            ram[0x30u] = (uint8_t)(source >> 8);
            ram[0x20e6u] = fg_read(fg, source);
            pair = fg_alg_shift_pair(fg,
                ram[0x20e5u], ram[0x20e6u], shift
            );
            ram[0x20e5u] = (uint8_t)(pair >> 8);
            ram[0x20e6u] = (uint8_t)pair;

            target = destination == 0x0400u ? 0x1000u : destination;
            fg_write(fg, target, ram[0x20e6u]);
            destination = (uint16_t)(destination + 1u);
            ram[0x3au] = (uint8_t)destination;
            ram[0x3bu] = (uint8_t)(destination >> 8);
            --remaining;
            ram[0x20d8u] = (uint8_t)remaining;
        }

        ram[0x20d0u] = (uint8_t)(column & 7u);
        if ((ram[0x2083u] & 7u) >= ram[0x20d0u]) {
            ram[0x20e5u] = fg_read(fg, source);
            source = (uint16_t)(source + 1u);
            ram[0x2fu] = (uint8_t)source;
            ram[0x30u] = (uint8_t)(source >> 8);
            ram[0x20e6u] = fg_read(fg, source);
        } else {
            ram[0x20e5u] = fg_read(fg, source);
            ram[0x20e6u] = 0u;
        }
        pair = fg_alg_shift_pair(fg,
            ram[0x20e5u], ram[0x20e6u], shift
        );
        ram[0x20e5u] = (uint8_t)(pair >> 8);
        ram[0x20e6u] = (uint8_t)pair;
        ram[0x20e6u] = (uint8_t)(
            ram[0x20e6u] & (uint8_t)~ram[0x20e4u]
        );
        target = destination == 0x0400u ? 0x1000u : destination;
        value = (uint32_t)fg_read(fg, target) & ram[0x20e4u];
        value |= ram[0x20e6u];
        fg_write(fg, target, (uint8_t)value);

        low = (uint8_t)source;
        sum = (uint32_t)low + 1u;
        source = (uint16_t)(source + 1u);
        ram[0x2fu] = (uint8_t)source;
        ram[0x30u] = (uint8_t)(source >> 8);
        carry = (uint8_t)(sum >> 8);
        high = (uint8_t)((source - 1u) >> 8);
        high_result = (uint8_t)(high + carry);
        overflow = fg_alg_add_high_overflow(fg,
            high, high_result
        );

        ram[0x3au] = ram[0x20e9u];
        ram[0x3bu] = ram[0x20eau];
        ram[0x100u | stack_pointer] = 0x6cu;
        ram[0x100u | (uint8_t)(stack_pointer - 1u)] = 0x37u;

        if (row < 0x40u) {
            target = fg_alg_zp16(fg, ram, 0x3au);
            target = (uint16_t)(target - 0x20u);
            ram[0x3au] = (uint8_t)target;
            ram[0x3bu] = (uint8_t)(target >> 8);

            low = ram[0x38u];
            carry = (uint8_t)(low >= 0x20u);
            ram[0x38u] = (uint8_t)(low - 0x20u);
            high = ram[0x39u];
            high_result = (uint8_t)(high - (carry ? 0u : 1u));
            ram[0x39u] = high_result;
            overflow = fg_alg_sub_high_overflow(fg,
                high, high_result
            );
        } else if (row == 0x40u) {
            low = ram[0x3au];
            carry = (uint8_t)(low >= 0x20u);
            ram[0x3au] = (uint8_t)(low - 0x20u);
            high = ram[0x3bu];
            high_result = (uint8_t)(high - (carry ? 0u : 1u));
            ram[0x3bu] = high_result;
            overflow = fg_alg_sub_high_overflow(fg,
                high, high_result
            );
            ram[0x38u] = 0xf3u;
            ram[0x39u] = 0x0fu;
        } else if (row == 0x41u) {
            ram[0x38u] = 0x33u;
            ram[0x39u] = 0x0cu;
            ram[0x3au] = 0x40u;
            ram[0x3bu] = 0x0cu;
            if (column >= 8u) {
                uint8_t offset = (uint8_t)(column - 8u);
                uint8_t increments = (uint8_t)(offset >> 3);

                ram[0x20b7u] = (uint8_t)(offset & 7u);
                target = (uint16_t)(0x0c40u + increments);
                ram[0x3au] = (uint8_t)target;
                ram[0x3bu] = (uint8_t)(target >> 8);
                overflow = 0u;
            }
        } else {
            target = fg_alg_zp16(fg, ram, 0x3au);
            target = (uint16_t)(target + 0x20u);
            ram[0x3au] = (uint8_t)target;
            ram[0x3bu] = (uint8_t)(target >> 8);

            low = ram[0x38u];
            sum = (uint32_t)low + 0x20u;
            carry = (uint8_t)(sum >> 8);
            ram[0x38u] = (uint8_t)sum;
            high = ram[0x39u];
            high_result = (uint8_t)(high + carry);
            ram[0x39u] = high_result;
            overflow = fg_alg_add_high_overflow(fg,
                high, high_result
            );
        }

        ram[0x20e9u] = ram[0x3au];
        ram[0x20eau] = ram[0x3bu];
        ram[0x2082u] = (uint8_t)(row + 1u);
        ram[0x20dau] = (uint8_t)(ram[0x20dau] - 1u);
        value = ram[0x20dau];
        status_value &= ~0xc3u;
        status_value |= 0x01u | (overflow ? 0x40u : 0u) |
            (value & 0x80u) | (value ? 0u : 0x02u);

        if (!value) {
            stack_pointer = (uint8_t)(stack_pointer + 1u);
            return_pc = ram[0x100u | stack_pointer];
            stack_pointer = (uint8_t)(stack_pointer + 1u);
            return_pc = (uint16_t)(
                return_pc |
                ((uint16_t)ram[0x100u | stack_pointer] << 8)
            );
            return_pc = (uint16_t)(return_pc + 1u);
            break;
        }
        if ((fg->ram[0x200u] & 8u))
            break;
    }

    if (!rows)
        return failure;
    result->cycles = cycles;
    result->rows = rows;
    result->pc = return_pc;
    result->ac = ram[0x20dau];
    result->ix = 0u;
    result->iy = 0u;
    result->sp = stack_pointer;
    result->status = (uint8_t)status_value;
    return 1;
}

FG_INLINE int fg_alg_picture_tail(fg_env_t *fg, int has_next_source_byte, uint32_t sp, uint32_t status,
    uint32_t cycle_budget, fg_region_result_t *result)
{
    uint8_t *ram = fg->ram;
    uint32_t cycles;
    uint32_t pair;
    uint32_t sum;
    uint32_t status_value = status & 0xffu;
    uint16_t source = fg_alg_zp16(fg, ram, 0x2fu);
    uint16_t destination = fg_alg_zp16(fg, ram, 0x3au);
    uint16_t target;
    uint16_t return_pc;
    uint8_t shift = ram[0x20cfu];
    uint8_t picture_mode = ram[0x20e7u];
    uint8_t row = ram[0x2082u];
    uint8_t column = ram[0x2081u];
    uint8_t stack_pointer = (uint8_t)sp;
    uint8_t low;
    uint8_t high;
    uint8_t carry;
    uint8_t high_result;
    uint8_t overflow;
    uint8_t remaining;

    /* Common unconverted-picture row suffix at E.BIN
     * $6B1A/$6BA4-$6C80.  Limit the native form to picture modes 3/4 and the
     * standard $0400 -> $1000 LCD alias; unusual mappings keep the original
     * path. */
    if (!ram[0x20dau] || (picture_mode != 3u && picture_mode != 4u) ||
        shift > 7u ||
        source < 0x0300u ||
        (uint32_t)source + (has_next_source_byte ? 2u : 1u) > 0x10000u ||
        destination < 0x0400u ||
        !fg_alg_region_write_safe(fg, destination, 1u) ||
        fg->page3[0xe5u] != 1u || fg->page3[0xe6u] != 0u ||
        fg->page3[0xe7u] != 4u || fg->page3[0xe8u] != 0u ||
        fg->page3[0xe9u] != 0x10u ||
        (!!has_next_source_byte !=
         ((ram[0x2083u] & 7u) >= (column & 7u))))
        return -1;

    cycles = has_next_source_byte
        ? 23u + fg_alg_shift_cost(fg, shift) + 14u +
            fg_alg_shift_masked_destination_cost(fg, destination)
        : 25u + fg_alg_shift_first_cost(fg, shift) + 14u +
            fg_alg_shift_low_tail_destination_cost(fg, destination);
    cycles += fg_alg_address_update_cycles(fg, row, column);
    cycles += ram[0x20dau] == 1u
        ? (picture_mode == 3u ? 100u : 106u)
        : (picture_mode == 3u ? 96u : 102u);
    /* In the production AOT chain, reaching $6988 after this suffix charges
     * 23/25 fewer cycles than instruction-by-instruction dispatcher re-entry.
     * Preserve that scheduling boundary as well as the architectural state. */
    cycles -= has_next_source_byte ? 23u : 25u;
    if (cycles > cycle_budget)
        return 0;

    ram[0x20e5u] = fg_read(fg, source);
    if (has_next_source_byte) {
        source = (uint16_t)(source + 1u);
        ram[0x2fu] = (uint8_t)source;
        ram[0x30u] = (uint8_t)(source >> 8);
        ram[0x20e6u] = fg_read(fg, source);
    } else {
        ram[0x20e6u] = 0u;
    }
    pair = fg_alg_shift_pair(fg,
        ram[0x20e5u], ram[0x20e6u], shift
    );
    ram[0x20e5u] = (uint8_t)(pair >> 8);
    ram[0x20e6u] = (uint8_t)pair;
    ram[0x20e6u] = (uint8_t)(
        ram[0x20e6u] & (uint8_t)~ram[0x20e4u]
    );
    target = destination == 0x0400u ? 0x1000u : destination;
    pair = (uint32_t)fg_read(fg, target) & ram[0x20e4u];
    pair |= ram[0x20e6u];
    fg_write(fg, target, (uint8_t)pair);

    low = (uint8_t)source;
    sum = (uint32_t)low + 1u;
    source = (uint16_t)(source + 1u);
    ram[0x2fu] = (uint8_t)source;
    ram[0x30u] = (uint8_t)(source >> 8);
    carry = (uint8_t)(sum >> 8);
    high = (uint8_t)((source - 1u) >> 8);
    high_result = (uint8_t)(high + carry);
    overflow = fg_alg_add_high_overflow(fg, high, high_result);

    ram[0x3au] = ram[0x20e9u];
    ram[0x3bu] = ram[0x20eau];
    /* Preserve the two stack bytes written by the real JSR $6646. */
    ram[0x100u | stack_pointer] = 0x6cu;
    ram[0x100u | (uint8_t)(stack_pointer - 1u)] = 0x37u;

    if (row < 0x40u) {
        target = fg_alg_zp16(fg, ram, 0x3au);
        target = (uint16_t)(target - 0x20u);
        ram[0x3au] = (uint8_t)target;
        ram[0x3bu] = (uint8_t)(target >> 8);

        low = ram[0x38u];
        carry = (uint8_t)(low >= 0x20u);
        ram[0x38u] = (uint8_t)(low - 0x20u);
        high = ram[0x39u];
        high_result = (uint8_t)(high - (carry ? 0u : 1u));
        ram[0x39u] = high_result;
        overflow = fg_alg_sub_high_overflow(fg, high, high_result);
    } else if (row == 0x40u) {
        low = ram[0x3au];
        carry = (uint8_t)(low >= 0x20u);
        ram[0x3au] = (uint8_t)(low - 0x20u);
        high = ram[0x3bu];
        high_result = (uint8_t)(high - (carry ? 0u : 1u));
        ram[0x3bu] = high_result;
        overflow = fg_alg_sub_high_overflow(fg, high, high_result);
        ram[0x38u] = 0xf3u;
        ram[0x39u] = 0x0fu;
    } else if (row == 0x41u) {
        ram[0x38u] = 0x33u;
        ram[0x39u] = 0x0cu;
        ram[0x3au] = 0x40u;
        ram[0x3bu] = 0x0cu;
        if (column >= 8u) {
            uint8_t offset = (uint8_t)(column - 8u);
            uint8_t increments = (uint8_t)(offset >> 3);

            ram[0x20b7u] = (uint8_t)(offset & 7u);
            target = (uint16_t)(0x0c40u + increments);
            ram[0x3au] = (uint8_t)target;
            ram[0x3bu] = (uint8_t)(target >> 8);
            overflow = 0u;
        }
    } else {
        target = fg_alg_zp16(fg, ram, 0x3au);
        target = (uint16_t)(target + 0x20u);
        ram[0x3au] = (uint8_t)target;
        ram[0x3bu] = (uint8_t)(target >> 8);

        low = ram[0x38u];
        sum = (uint32_t)low + 0x20u;
        carry = (uint8_t)(sum >> 8);
        ram[0x38u] = (uint8_t)sum;
        high = ram[0x39u];
        high_result = (uint8_t)(high + carry);
        ram[0x39u] = high_result;
        overflow = fg_alg_add_high_overflow(fg, high, high_result);
    }

    ram[0x20e9u] = ram[0x3au];
    ram[0x20eau] = ram[0x3bu];
    ram[0x2082u] = (uint8_t)(row + 1u);
    remaining = (uint8_t)(ram[0x20dau] - 1u);
    ram[0x20dau] = remaining;

    status_value &= ~0xc3u;
    status_value |= 0x01u | (overflow ? 0x40u : 0u) |
        (remaining & 0x80u) | (remaining ? 0u : 0x02u);
    if (remaining) {
        return_pc = picture_mode == 3u ? 0x6988u : 0x69d9u;
    } else {
        stack_pointer = (uint8_t)(stack_pointer + 1u);
        return_pc = ram[0x100u | stack_pointer];
        stack_pointer = (uint8_t)(stack_pointer + 1u);
        return_pc = (uint16_t)(
            return_pc | ((uint16_t)ram[0x100u | stack_pointer] << 8)
        );
        return_pc = (uint16_t)(return_pc + 1u);
    }

    result->cycles = cycles;
    result->rows = 1u;
    result->pc = return_pc;
    result->ac = remaining;
    result->ix = 0u;
    result->iy = 0u;
    result->sp = stack_pointer;
    result->status = (uint8_t)status_value;
    return 1;
}

FG_INLINE uint32_t fg_alg_bitmap_row_cycles(fg_env_t *fg, const uint8_t *ram)
{
    uint32_t width = ram[0x20e8u];
    uint32_t shift = ram[0x20cfu];
    uint32_t source = fg_alg_zp16(fg, ram, 0x2fu);
    uint32_t destination = fg_alg_zp16(fg, ram, 0x31u);
    uint32_t source_bytes = width ? width + 1u : 1u;
    uint32_t destination_bytes = width ? width + 1u : 1u;
    uint32_t common = ram[0x20dau] == 1u ? 67u : 63u;
    uint32_t first_shift;
    uint32_t inner_nonfinal;
    uint32_t inner_final;
    uint32_t tail;
    uint32_t cycles;

    /* The row estimator is side-effect free.  Limit the accelerated form to
     * ordinary source memory and the LCD/buffer window, which guarantees an
     * indirect write cannot alias the routine's zero-page/control fields. */
    if (source < 0x0300u || source + source_bytes > 0x10000u ||
        destination < 0x0400u ||
        destination + destination_bytes > 0x10000u ||
        (destination < 0x2100u &&
         destination + destination_bytes > 0x2000u))
        return 0u;
    if (!width)
        return 19u + (shift == 0u ? 64u : 62u + 19u * shift) + common;

    first_shift = shift == 0u ? 28u : 26u + 19u * shift;
    inner_nonfinal = shift == 0u ? 103u : 101u + 19u * shift;
    inner_final = shift == 0u ? 101u : 99u + 19u * shift;
    cycles = 17u + first_shift + 43u + (width == 1u ? 16u : 14u);
    if (width > 1u)
        cycles += (width - 2u) * inner_nonfinal + inner_final;
    if ((ram[0x2083u] & 7u) >= (ram[0x2081u] & 7u))
        tail = 22u + (shift == 0u ? 93u : 91u + 19u * shift);
    else
        tail = 23u + (shift == 0u ? 63u : 61u + 19u * shift);
    return cycles + tail + common;
}

FG_INLINE int fg_alg_bitmap_region(fg_env_t *fg, uint32_t sp, uint32_t status, uint32_t cycle_budget,
    fg_region_result_t *result)
{
    uint8_t *ram = fg->ram;
    uint32_t cycles = 0u;
    uint32_t rows = 0u;
    uint32_t status_value = status & 0xffu;
    uint32_t value;
    uint32_t sum;
    uint16_t address;
    uint16_t pair;
    uint8_t width;
    uint8_t remaining;
    uint8_t shift;
    uint8_t low;
    uint8_t high;
    uint8_t carry;
    int failure = 0;

    /* This is an instruction-order specialization of E.BIN
     * $5C5D-$5DC9, including its width-zero tail at $5DCA.  RAM control
     * fields are intentionally re-read after every indirect write so even
     * unusual aliasing follows the original routine rather than a cached
     * rectangle description. */
    for (;;) {
        uint32_t row_cycles = fg_alg_bitmap_row_cycles(fg, ram);

        if (!row_cycles) {
            failure = -1;
            break;
        }
        if (row_cycles > cycle_budget - cycles) {
            failure = 0;
            break;
        }
        ++rows;
        width = ram[0x20e8u];
        ram[0x20d8u] = width;
        cycles += 14u; /* LDA/STA/LDA/CMP */

        if (width) {
            cycles += 3u; /* taken BNE $5C6D */

            address = fg_alg_zp16(fg, ram, 0x2fu);
            ram[0x20e6u] = fg_read(fg, address);
            ram[0x20e5u] = 0u;
            shift = ram[0x20cfu];
            pair = fg_alg_shift_pair(fg,
                ram[0x20e5u], ram[0x20e6u], shift
            );
            ram[0x20e5u] = (uint8_t)(pair >> 8);
            ram[0x20e6u] = (uint8_t)pair;
            cycles += shift == 0u ? 28u : 26u + 19u * shift;

            address = fg_alg_zp16(fg, ram, 0x31u);
            value = (uint32_t)fg_read(fg, address) & ram[0x20e3u];
            value |= ram[0x20e6u];
            fg_write(fg, address, (uint8_t)value);
            cycles += 21u;

            sum = (uint32_t)ram[0x31u] + 1u;
            ram[0x31u] = (uint8_t)sum;
            sum = (uint32_t)ram[0x32u] + (sum >> 8);
            ram[0x32u] = (uint8_t)sum;
            cycles += 22u;

            remaining = (uint8_t)(ram[0x20d8u] - 1u);
            ram[0x20d8u] = remaining;
            cycles += remaining ? 14u : 16u;

            while (remaining) {
                address = fg_alg_zp16(fg, ram, 0x2fu);
                ram[0x20e5u] = fg_read(fg, address);
                sum = (uint32_t)ram[0x2fu] + 1u;
                ram[0x2fu] = (uint8_t)sum;
                sum = (uint32_t)ram[0x30u] + (sum >> 8);
                ram[0x30u] = (uint8_t)sum;
                address = fg_alg_zp16(fg, ram, 0x2fu);
                ram[0x20e6u] = fg_read(fg, address);

                shift = ram[0x20cfu];
                pair = fg_alg_shift_pair(fg,
                    ram[0x20e5u], ram[0x20e6u], shift
                );
                ram[0x20e5u] = (uint8_t)(pair >> 8);
                ram[0x20e6u] = (uint8_t)pair;

                address = fg_alg_zp16(fg, ram, 0x31u);
                fg_write(fg, address, ram[0x20e6u]);
                sum = (uint32_t)ram[0x31u] + 1u;
                ram[0x31u] = (uint8_t)sum;
                sum = (uint32_t)ram[0x32u] + (sum >> 8);
                ram[0x32u] = (uint8_t)sum;

                remaining = (uint8_t)(ram[0x20d8u] - 1u);
                ram[0x20d8u] = remaining;
                cycles += (shift == 0u ? 55u : 53u + 19u * shift) +
                    32u + (remaining ? 16u : 14u);
            }

            ram[0x20d0u] = (uint8_t)(ram[0x2081u] & 7u);
            if ((ram[0x2083u] & 7u) >= ram[0x20d0u]) {
                cycles += 22u;
                address = fg_alg_zp16(fg, ram, 0x2fu);
                ram[0x20e5u] = fg_read(fg, address);
                sum = (uint32_t)ram[0x2fu] + 1u;
                ram[0x2fu] = (uint8_t)sum;
                sum = (uint32_t)ram[0x30u] + (sum >> 8);
                ram[0x30u] = (uint8_t)sum;
                address = fg_alg_zp16(fg, ram, 0x2fu);
                ram[0x20e6u] = fg_read(fg, address);
                shift = ram[0x20cfu];
                pair = fg_alg_shift_pair(fg,
                    ram[0x20e5u], ram[0x20e6u], shift
                );
                ram[0x20e5u] = (uint8_t)(pair >> 8);
                ram[0x20e6u] = (uint8_t)pair;
                ram[0x20e6u] = (uint8_t)(
                    ram[0x20e6u] & (uint8_t)~ram[0x20e4u]
                );
                address = fg_alg_zp16(fg, ram, 0x31u);
                value = (uint32_t)fg_read(fg, address) & ram[0x20e4u];
                value |= ram[0x20e6u];
                fg_write(fg, address, (uint8_t)value);
                cycles += shift == 0u ? 93u : 91u + 19u * shift;
            } else {
                cycles += 23u;
                address = fg_alg_zp16(fg, ram, 0x2fu);
                ram[0x20e5u] = fg_read(fg, address);
                ram[0x20e6u] = 0u;
                shift = ram[0x20cfu];
                pair = fg_alg_shift_pair(fg,
                    ram[0x20e5u], ram[0x20e6u], shift
                );
                ram[0x20e5u] = (uint8_t)(pair >> 8);
                ram[0x20e6u] = (uint8_t)pair;
                ram[0x20e6u] = (uint8_t)(
                    ram[0x20e6u] & (uint8_t)~ram[0x20e4u]
                );
                address = fg_alg_zp16(fg, ram, 0x31u);
                value = (uint32_t)fg_read(fg, address) & ram[0x20e4u];
                value |= ram[0x20e6u];
                fg_write(fg, address, (uint8_t)value);
                cycles += shift == 0u ? 63u : 61u + 19u * shift;
            }
        } else {
            cycles += 5u; /* not-taken BNE plus JMP $5DCA */
            ram[0x20e3u] = (uint8_t)(ram[0x20e3u] | ram[0x20e4u]);
            address = fg_alg_zp16(fg, ram, 0x2fu);
            ram[0x20e6u] = fg_read(fg, address);
            ram[0x20e5u] = 0u;
            shift = ram[0x20cfu];
            pair = fg_alg_shift_pair(fg,
                ram[0x20e5u], ram[0x20e6u], shift
            );
            ram[0x20e5u] = (uint8_t)(pair >> 8);
            ram[0x20e6u] = (uint8_t)pair;
            address = fg_alg_zp16(fg, ram, 0x31u);
            value = (uint32_t)fg_read(fg, address) & ram[0x20e3u];
            value |= ram[0x20e6u];
            fg_write(fg, address, (uint8_t)value);
            cycles += shift == 0u ? 64u : 62u + 19u * shift;
        }

        sum = (uint32_t)ram[0x2fu] + 1u;
        ram[0x2fu] = (uint8_t)sum;
        sum = (uint32_t)ram[0x30u] + (sum >> 8);
        ram[0x30u] = (uint8_t)sum;
        cycles += 22u;

        low = ram[0x31u];
        sum = (uint32_t)ram[0x20deu] + low;
        ram[0x31u] = (uint8_t)sum;
        carry = (uint8_t)(sum >> 8);
        high = ram[0x32u];
        sum = (uint32_t)high + carry;
        ram[0x32u] = (uint8_t)sum;
        status_value &= ~0x40u;
        if (high == 0x7fu && carry)
            status_value |= 0x40u;
        cycles += 24u;

        ram[0x20dau] = (uint8_t)(ram[0x20dau] - 1u);
        if (ram[0x20dau])
            cycles += 17u; /* DEC/LDA/CMP, not-taken BEQ, JMP */
        else
            cycles += 21u; /* DEC/LDA/CMP, taken BEQ, RTS */
        if (!ram[0x20dau] || (fg->ram[0x200u] & 8u))
            break;
    }

    if (!rows)
        return failure;
    result->cycles = cycles;
    result->rows = rows;
    result->ix = 0u;
    result->iy = 0u;
    if (!ram[0x20dau]) {
        status_value = (status_value & ~0x83u) | 0x03u;
        sp = (uint8_t)(sp + 1u);
        address = ram[0x100u | (uint8_t)sp];
        sp = (uint8_t)(sp + 1u);
        address = (uint16_t)(
            address | ((uint16_t)ram[0x100u | (uint8_t)sp] << 8)
        );
        result->pc = (uint16_t)(address + 1u);
        result->ac = 0u;
        result->sp = (uint8_t)sp;
        result->status = (uint8_t)status_value;
    } else {
        value = ram[0x20dau];
        status_value = (status_value & ~0x83u) | 0x01u | (value & 0x80u);
        result->pc = 0x5c5du;
        result->ac = (uint8_t)value;
        result->sp = (uint8_t)sp;
        result->status = (uint8_t)status_value;
    }
    return 1;
}

FG_INLINE int fg_alg_graphics_address(fg_env_t *fg, uint32_t ix, uint32_t iy, uint32_t sp, uint32_t status,
    uint32_t cycle_budget, fg_direct_result_t *result)
{
    uint8_t *ram = fg->ram;
    uint8_t x = ram[0x2081u];
    uint8_t row = ram[0x2082u];
    uint8_t stack_pointer = (uint8_t)sp;
    uint8_t p = (uint8_t)status;
    uint8_t a;
    uint8_t y = (uint8_t)iy;
    uint8_t product_low = 0u;
    uint8_t product_high = 0u;
    uint8_t multiplier = 0u;
    uint8_t destination_low = 0u;
    uint8_t destination_high = 0u;
    uint8_t left_low = 0u;
    uint8_t left_high = 0u;
    uint8_t column_remainder = ram[0x20b7u];
    uint16_t return_address = (uint16_t)(
        ram[0x100u | (uint8_t)(stack_pointer + 1u)] |
        (ram[0x100u | (uint8_t)(stack_pointer + 2u)] << 8));
    uint16_t internal_return = 0u;
    uint32_t cycles = 0u;

    a = row;
    p = fg_alg_nz(fg, p, a);
    cycles += 4u;
    p = (uint8_t)((p & ~0x83u) | (a >= 0x41u) |
        ((uint8_t)(a - 0x41u) & 0x80u) |
        (a == 0x41u ? 0x02u : 0u));
    cycles += 2u;
    if (row == 0x41u) {
        cycles += 2u + 3u;
        a = 0xf3u;
        p = fg_alg_nz(fg, p, a);
        left_low = a;
        a = 0x0fu;
        p = fg_alg_nz(fg, p, a);
        left_high = a;
        a = 0u;
        p = fg_alg_nz(fg, p, a);
        destination_low = a;
        a = 4u;
        p = fg_alg_nz(fg, p, a);
        destination_high = a;
        cycles += 24u;
    } else {
        cycles += 3u;
        if (row > 0x41u) {
            cycles += 2u;
            p |= 1u;
            cycles += 2u;
            a = row;
            p = fg_alg_nz(fg, p, a);
            cycles += 4u;
            p = fg_alg_sbc8(fg, p, a, 0x42u, &a);
            cycles += 2u;
            multiplier = a;
            cycles += 4u;
            a = 0x20u;
            p = fg_alg_nz(fg, p, a);
            product_low = a;
            cycles += 12u;
            internal_return = 0x8787u;
        } else {
            cycles += 3u;
            a = row;
            p = fg_alg_nz(fg, p, a);
            multiplier = a;
            a = 0x20u;
            p = fg_alg_nz(fg, p, a);
            product_low = a;
            cycles += 4u + 4u + 2u + 4u + 6u;
            internal_return = 0x87ecu;
        }

        /* Exact $7C29 8-bit multiply, including its flag and cycle path. */
        a = 0u;
        p = fg_alg_nz(fg, p, a);
        product_high = a;
        y = 8u;
        p = fg_alg_nz(fg, p, y);
        cycles += 8u;
        do {
            uint8_t carry = (uint8_t)(product_high >> 7);

            product_high = (uint8_t)(product_high << 1);
            p = fg_alg_nz(fg, p, product_high);
            p = (uint8_t)((p & ~1u) | carry);
            cycles += 6u;
            carry = (uint8_t)(multiplier >> 7);
            multiplier = (uint8_t)((multiplier << 1) | (p & 1u));
            p = fg_alg_nz(fg, p, multiplier);
            p = (uint8_t)((p & ~1u) | carry);
            cycles += 6u;
            if (!(p & 1u)) {
                cycles += 3u;
            } else {
                cycles += 2u;
                p &= (uint8_t)~1u;
                cycles += 2u;
                a = product_low;
                p = fg_alg_nz(fg, p, a);
                cycles += 4u;
                p = fg_alg_adc8(fg,
                    p, a, product_high, &a);
                cycles += 4u;
                product_high = a;
                cycles += 4u;
                if (p & 1u) {
                    cycles += 2u;
                    multiplier = (uint8_t)(multiplier + 1u);
                    p = fg_alg_nz(fg, p, multiplier);
                    cycles += 6u;
                } else {
                    cycles += 3u;
                }
            }
            y = (uint8_t)(y - 1u);
            p = fg_alg_nz(fg, p, y);
            cycles += 2u + (y ? 3u : 2u);
        } while (y);
        cycles += 6u;

        if (row > 0x41u) {
            p &= (uint8_t)~1u;
            a = 0x40u;
            p = fg_alg_nz(fg, p, a);
            p = fg_alg_adc8(fg, p, a, product_high, &a);
            destination_low = a;
            a = 0x0cu;
            p = fg_alg_nz(fg, p, a);
            p = fg_alg_adc8(fg, p, a, multiplier, &a);
            destination_high = a;
            cycles += 2u + 2u + 4u + 4u + 2u + 4u + 4u;
        } else {
            p |= 1u;
            a = 0x20u;
            p = fg_alg_nz(fg, p, a);
            p = fg_alg_sbc8(fg, p, a, product_high, &a);
            destination_low = a;
            a = 0x0cu;
            p = fg_alg_nz(fg, p, a);
            p = fg_alg_sbc8(fg, p, a, multiplier, &a);
            destination_high = a;
            cycles += 2u + 2u + 4u + 4u + 2u + 4u + 4u;
        }
        p |= 1u;
        a = destination_low;
        p = fg_alg_nz(fg, p, a);
        p = fg_alg_sbc8(fg, p, a, 0x0du, &a);
        left_low = a;
        a = destination_high;
        p = fg_alg_nz(fg, p, a);
        p = fg_alg_sbc8(fg, p, a, 0u, &a);
        left_high = a;
        cycles += 2u + 4u + 2u + 4u + 4u + 2u + 4u;
    }

    a = x;
    p = fg_alg_nz(fg, p, a);
    cycles += 4u;
    p = (uint8_t)((p & ~0x83u) | (a >= 8u) |
        ((uint8_t)(a - 8u) & 0x80u) | (a == 8u ? 0x02u : 0u));
    cycles += 2u;
    if (x < 8u) {
        cycles += 2u + 3u + 6u;
    } else {
        cycles += 3u;
        p |= 1u;
        cycles += 2u;
        a = x;
        p = fg_alg_nz(fg, p, a);
        cycles += 4u;
        p = fg_alg_sbc8(fg, p, a, 8u, &a);
        cycles += 2u;
        column_remainder = a;
        cycles += 4u;
        for (;;) {
            p |= 1u;
            cycles += 2u;
            a = column_remainder;
            p = fg_alg_nz(fg, p, a);
            cycles += 4u;
            p = fg_alg_sbc8(fg, p, a, 8u, &a);
            cycles += 2u;
            if (!(p & 1u)) {
                cycles += row > 0x41u ? 2u + 3u : 3u;
                break;
            }
            cycles += row > 0x41u ? 3u : 2u;
            column_remainder = a;
            cycles += 4u;
            p &= (uint8_t)~1u;
            cycles += 2u;
            a = 1u;
            p = fg_alg_nz(fg, p, a);
            cycles += 2u;
            p = fg_alg_adc8(fg,
                p, a, destination_low, &a);
            destination_low = a;
            cycles += 4u + 4u;
            a = 0u;
            p = fg_alg_nz(fg, p, a);
            cycles += 2u;
            p = fg_alg_adc8(fg,
                p, a, destination_high, &a);
            destination_high = a;
            cycles += 4u + 4u + 3u;
        }
        cycles += 6u;
    }
    if (cycles > cycle_budget)
        return 0;

    if (internal_return) {
        ram[0x2085u] = multiplier;
        ram[0x2087u] = product_low;
        ram[0x2089u] = product_high;
    }
    ram[0x3au] = destination_low;
    ram[0x3bu] = destination_high;
    ram[0x38u] = left_low;
    ram[0x39u] = left_high;
    ram[0x20b7u] = column_remainder;
    if (internal_return) {
        ram[0x100u | stack_pointer] = (uint8_t)(internal_return >> 8);
        ram[0x100u | (uint8_t)(stack_pointer - 1u)] =
            (uint8_t)internal_return;
    }
    result->cycles = cycles;
    result->pc = (uint16_t)(return_address + 1u);
    result->ac = a;
    result->ix = (uint8_t)ix;
    result->iy = y;
    result->dt = (uint8_t)(stack_pointer + 2u);
    result->status = p;
    return 1;
}

FG_INLINE int fg_alg_hline_middle(fg_env_t *fg, uint32_t ac, uint32_t ix, uint32_t iy, uint32_t sp, uint32_t status,
    uint32_t cycle_budget, fg_direct_result_t *result)
{
    uint8_t *ram = fg->ram;
    uint16_t destination = (uint16_t)(ram[0x3au] | (ram[0x3bu] << 8));
    uint8_t remaining = ram[0x20d8u];
    uint8_t p = (uint8_t)status;
    uint32_t cycles = 0u;
    uint32_t hits = 0u;

    (void)ac;
    if (!remaining)
        return -1;
    for (;;) {
        uint8_t alias_enabled = fg_read(fg, 0x03e5u);
        uint8_t alias_low = fg_read(fg, 0x03e6u);
        uint8_t alias_high = fg_read(fg, 0x03e7u);
        uint8_t next_remaining = (uint8_t)(remaining - 1u);
        uint32_t iteration_cycles;
        int use_alias = alias_enabled == 1u &&
            (uint8_t)(destination >> 8) == alias_high &&
            (uint8_t)destination == alias_low;

        if (alias_enabled != 1u)
            iteration_cycles = 17u;
        else if ((uint8_t)(destination >> 8) != alias_high)
            iteration_cycles = 27u;
        else if ((uint8_t)destination != alias_low)
            iteration_cycles = 37u;
        else
            iteration_cycles = 71u;
        iteration_cycles += next_remaining ? 37u : 36u;
        if (iteration_cycles > cycle_budget - cycles)
            break;

        if (use_alias) {
            uint16_t alternate = (uint16_t)(
                fg_read(fg, 0x03e8u) | (fg_read(fg, 0x03e9u) << 8));

            fg_write(fg, alternate, 0xffu);
        } else {
            fg_write(fg, destination, 0xffu);
        }
        p = (uint8_t)((p & ~0x40u) |
            (((uint8_t)destination == 0xffu &&
              (uint8_t)(destination >> 8) == 0x7fu) ? 0x40u : 0u));
        destination = (uint16_t)(destination + 1u);
        remaining = next_remaining;
        cycles += iteration_cycles;
        ++hits;
        if (!remaining)
            break;
    }
    if (!hits)
        return 0;

    ram[0x3au] = (uint8_t)destination;
    ram[0x3bu] = (uint8_t)(destination >> 8);
    ram[0x20d8u] = remaining;
    p = (uint8_t)((p & ~0x83u) | 1u | (remaining & 0x80u) |
        (remaining ? 0u : 0x02u));
    result->cycles = cycles;
    result->hits = hits;
    result->pc = remaining ? 0x8039u : 0x808eu;
    result->ea = destination;
    result->ac = remaining;
    result->ix = (uint8_t)ix;
    result->iy = (uint8_t)iy;
    result->dt = (uint8_t)sp;
    result->status = p;
    return 1;
}

FG_INLINE int fg_alg_part_picture_row(fg_env_t *fg, int shift_left, uint32_t ac, uint32_t iy, uint32_t sp, uint32_t status,
    uint32_t cycle_budget, fg_direct_result_t *result)
{
    uint8_t *ram = fg->ram;
    uint16_t source = (uint16_t)(ram[0x2fu] | (ram[0x30u] << 8));
    uint16_t destination = (uint16_t)(ram[0x3au] | (ram[0x3bu] << 8));
    uint8_t remaining = ram[0x20d8u];
    uint8_t shift = ram[0x20cfu];
    uint8_t p = (uint8_t)status;
    uint8_t high = ram[0x20e5u];
    uint8_t low = ram[0x20e6u];
    uint32_t cycles = 0u;
    uint32_t hits = 0u;

    (void)ac;
    if (!remaining || shift > 7u)
        return -1;
    for (;;) {
        uint8_t alias_enabled = fg_read(fg, 0x03e5u);
        uint8_t alias_low = fg_read(fg, 0x03e6u);
        uint8_t alias_high = fg_read(fg, 0x03e7u);
        uint8_t next_remaining = (uint8_t)(remaining - 1u);
        uint16_t old_destination = destination;
        uint32_t shift_cycles = shift ? 53u + 19u * shift : 55u;
        uint32_t write_cycles;
        uint32_t iteration_cycles;
        int use_alias = alias_enabled == 1u &&
            (uint8_t)(destination >> 8) == alias_high &&
            (uint8_t)destination == alias_low;

        if (alias_enabled != 1u)
            write_cycles = 19u;
        else if ((uint8_t)(destination >> 8) != alias_high)
            write_cycles = 29u;
        else if ((uint8_t)destination != alias_low)
            write_cycles = 39u;
        else
            write_cycles = 73u;
        iteration_cycles = shift_cycles + write_cycles +
            (next_remaining ? 39u : 37u);
        if (iteration_cycles > cycle_budget - cycles)
            break;

        high = fg_read(fg, source);
        source = (uint16_t)(source + 1u);
        low = fg_read(fg, source);
        if (shift_left) {
            uint16_t pair = (uint16_t)((high << 8) | low);

            pair = (uint16_t)(pair << shift);
            high = (uint8_t)(pair >> 8);
            low = (uint8_t)pair;
        } else {
            uint16_t pair = (uint16_t)((high << 8) | low);

            pair = (uint16_t)(pair >> shift);
            high = (uint8_t)(pair >> 8);
            low = (uint8_t)pair;
        }
        if (use_alias) {
            uint16_t alternate = (uint16_t)(
                fg_read(fg, 0x03e8u) | (fg_read(fg, 0x03e9u) << 8));

            fg_write(fg, alternate, shift_left ? high : low);
        } else {
            fg_write(fg, destination, shift_left ? high : low);
        }
        p = (uint8_t)((p & ~0x40u) |
            (((uint8_t)old_destination == 0xffu &&
              (uint8_t)(old_destination >> 8) == 0x7fu) ? 0x40u : 0u));
        destination = (uint16_t)(destination + 1u);
        remaining = next_remaining;
        cycles += iteration_cycles;
        ++hits;
        if (!remaining)
            break;
    }
    if (!hits)
        return 0;

    ram[0x2fu] = (uint8_t)source;
    ram[0x30u] = (uint8_t)(source >> 8);
    ram[0x3au] = (uint8_t)destination;
    ram[0x3bu] = (uint8_t)(destination >> 8);
    ram[0x20e5u] = high;
    ram[0x20e6u] = low;
    ram[0x20d8u] = remaining;
    p = (uint8_t)((p & ~0x83u) | 1u | (remaining & 0x80u) |
        (remaining ? 0u : 0x02u));
    result->cycles = cycles;
    result->hits = hits;
    result->pc = remaining ? (shift_left ? 0x5801u : 0x5351u) :
        (shift_left ? 0x588du : 0x53ddu);
    result->ea = destination;
    result->ac = remaining;
    result->ix = 0u;
    result->iy = 0u;
    result->dt = (uint8_t)sp;
    result->status = p;
    return 1;
}

FG_INLINE int fg_alg_pixel_tail(fg_env_t *fg, uint32_t sp, uint32_t status, uint32_t cycle_budget,
    fg_direct_result_t *result)
{
    uint8_t *ram = fg->ram;
    uint8_t x = ram[0x2081u];
    uint8_t bit = (uint8_t)(x & 7u);
    uint8_t mask = (uint8_t)(0x80u >> bit);
    uint8_t inverse = (uint8_t)~mask;
    uint8_t p = (uint8_t)status;
    uint8_t stack_pointer = (uint8_t)sp;
    uint8_t final_a;
    uint16_t destination;
    uint16_t return_address = (uint16_t)(
        ram[0x100u | (uint8_t)(stack_pointer + 1u)] |
        (ram[0x100u | (uint8_t)(stack_pointer + 2u)] << 8));
    uint32_t cycles = 21u + 17u * bit;
    int alias = 0;

    cycles += x < 8u ? 20u : 18u;
    if (x < 8u) {
        destination = (uint16_t)(ram[0x38u] | (ram[0x39u] << 8));
        cycles += ram[0x2080u] ? 32u : 29u;
    } else {
        uint8_t alias_enabled = fg_read(fg, 0x03e5u);

        if (alias_enabled != 1u) {
            cycles += 10u;
        } else {
            uint8_t destination_high = ram[0x3bu];
            uint8_t alias_high = fg_read(fg, 0x03e7u);

            cycles += 8u;
            if (destination_high != alias_high) {
                cycles += 12u;
            } else {
                uint8_t destination_low = ram[0x3au];
                uint8_t alias_low = fg_read(fg, 0x03e6u);

                cycles += 10u;
                if (destination_low != alias_low) {
                    cycles += 12u;
                } else {
                    alias = 1;
                    cycles += 26u;
                }
            }
        }
        if (alias) {
            cycles += ram[0x2080u] ? 54u : 48u;
            destination = (uint16_t)(
                fg_read(fg, 0x03e8u) | (fg_read(fg, 0x03e9u) << 8));
        } else {
            cycles += ram[0x2080u] ? 32u : 29u;
            destination = (uint16_t)(ram[0x3au] | (ram[0x3bu] << 8));
        }
    }
    cycles += 6u;
    if (cycles > cycle_budget)
        return 0;

    ram[0x20b8u] = mask;
    ram[0x20b9u] = inverse;
    final_a = (uint8_t)(fg_read(fg, destination) & inverse);
    if (ram[0x2080u])
        final_a = (uint8_t)(final_a | mask);
    fg_write(fg, destination, final_a);
    if (alias) {
        ram[0x3au] = fg_read(fg, 0x03e6u);
        ram[0x3bu] = fg_read(fg, 0x03e7u);
        final_a = ram[0x3bu];
    }
    p = fg_alg_nz(fg, p, final_a);
    /* The final CMP #$00 that selects set/clear mode always leaves C set. */
    p |= 1u;

    result->cycles = cycles;
    result->hits = 1u;
    result->pc = (uint16_t)(return_address + 1u);
    result->ea = destination;
    result->ac = final_a;
    result->ix = 0u;
    result->iy = 0u;
    result->dt = (uint8_t)(stack_pointer + 2u);
    result->status = p;
    return 1;
}

FG_INLINE int fg_alg_picture_head(fg_env_t *fg, uint32_t ac, uint32_t iy, uint32_t sp, uint32_t status,
    uint32_t cycle_budget, fg_direct_result_t *result)
{
    uint8_t *ram = fg->ram;
    uint16_t argument_pointer = fg_alg_zp16(fg, ram, 0x28u);
    uint32_t cycles = 0u;
    uint8_t x1 = (uint8_t)ac;
    uint8_t y1 = fg_read(fg, argument_pointer);
    uint8_t x2 = fg_read(fg, (uint16_t)(argument_pointer + 1u));
    uint8_t y2 = fg_read(fg, (uint16_t)(argument_pointer + 2u));
    uint8_t flag = fg_read(fg, (uint16_t)(argument_pointer + 5u));
    uint8_t shift;
    uint8_t right_shift;
    uint8_t temporary;
    uint8_t stack_pointer = (uint8_t)sp;
    uint8_t pointer_low = (uint8_t)argument_pointer;

    (void)iy;
    if (x2 >= 0xa0u || y2 >= 0x60u || flag != 0u)
        return -1;

    cycles += 4u + 2u;
    cycles += fg_alg_indirect_y_cycles(fg, pointer_low, 0u) + 4u;
    cycles += 2u +
        fg_alg_indirect_y_cycles(fg, pointer_low, 1u) + 4u + 2u + 3u;
    if (x2 < x1)
        cycles += 15u;
    cycles += 2u +
        fg_alg_indirect_y_cycles(fg, pointer_low, 2u) + 4u + 2u + 3u;
    if (y2 < y1)
        cycles += 15u;
    cycles += 2u +
        fg_alg_indirect_y_cycles(fg, pointer_low, 3u) + 4u;
    cycles += 2u +
        fg_alg_indirect_y_cycles(fg, pointer_low, 4u) + 4u;
    cycles += 2u +
        fg_alg_indirect_y_cycles(fg, pointer_low, 5u) + 2u + 3u;

    if (x2 < x1) {
        temporary = x1;
        x1 = x2;
        x2 = temporary;
    }
    if (y2 < y1) {
        temporary = y1;
        y1 = y2;
        y2 = temporary;
    }
    shift = (uint8_t)(x1 & 7u);
    right_shift = (uint8_t)(7u - (x2 & 7u));
    cycles += 22u + (shift ? 15u * shift + 4u : 9u);
    cycles += 28u + (right_shift ? 15u * right_shift + 4u : 9u);
    /* $68D3-$690C, including both absolute read/modify/write sequences and
     * the six-cycle JSR at the boundary. */
    cycles += 26u + 14u + 14u + 46u;
    if (cycles > cycle_budget)
        return 0;

    ram[0x2081u] = x1;
    ram[0x2082u] = y1;
    ram[0x2083u] = x2;
    ram[0x2084u] = y2;
    ram[0x2fu] = fg_read(fg, (uint16_t)(argument_pointer + 3u));
    ram[0x30u] = fg_read(fg, (uint16_t)(argument_pointer + 4u));
    ram[0x20cfu] = shift;
    ram[0x20e3u] = shift ? (uint8_t)(0xffu << (8u - shift)) : 0u;
    ram[0x20e4u] = right_shift
        ? (uint8_t)(0xffu >> (8u - right_shift)) : 0u;
    ram[0x20dau] = (uint8_t)(y2 - y1 + 1u);
    ram[0x20e5u] = (uint8_t)(x1 >> 3);
    ram[0x20e6u] = (uint8_t)(x2 >> 3);
    ram[0x20d8u] = (uint8_t)(ram[0x20e6u] - ram[0x20e5u]);
    ram[0x20e8u] = ram[0x20d8u];
    ram[0x20e7u] = 0u;
    ram[0x100u | stack_pointer] = 0x69u;
    ram[0x100u | (uint8_t)(stack_pointer - 1u)] = 0x0eu;

    result->cycles = cycles;
    result->pc = 0x876bu;
    result->ac = 0u;
    result->ix = 0u;
    result->iy = 5u;
    result->dt = (uint8_t)(stack_pointer - 2u);
    result->status = (uint8_t)((status & ~0xc3u) | 0x03u);
    return 1;
}

FG_INLINE int fg_alg_picture_resume(fg_env_t *fg, uint32_t ac, uint32_t ix, uint32_t iy, uint32_t sp, uint32_t status,
    uint32_t cycle_budget, fg_direct_result_t *result)
{
    uint8_t *ram = fg->ram;
    uint8_t x = ram[0x2081u];
    uint8_t y = ram[0x2082u];
    uint32_t cycles = 16u + 4u + 2u;
    uint16_t next_pc;
    uint8_t compare = (uint8_t)(x - 8u);

    (void)ac;
    if (y == 0x41u) {
        cycles += 3u + 4u + 2u;
        if (x < 8u) {
            cycles += 3u;
            next_pc = 0x6930u;
        } else {
            cycles += 2u + 3u;
            next_pc = 0x69d9u;
        }
    } else {
        cycles += 2u + 3u + 4u + 2u;
        if (x < 8u) {
            cycles += 2u;
            next_pc = 0x6988u;
        } else {
            cycles += 3u;
            next_pc = 0x69d9u;
        }
    }
    if (cycles > cycle_budget)
        return 0;

    ram[0x20e9u] = ram[0x3au];
    ram[0x20eau] = ram[0x3bu];
    status &= ~0x83u;
    status |= x >= 8u ? 0x01u : 0u;
    status |= compare ? 0u : 0x02u;
    status |= compare & 0x80u;
    result->cycles = cycles;
    result->pc = next_pc;
    result->ac = x;
    result->ix = (uint8_t)ix;
    result->iy = (uint8_t)iy;
    result->dt = (uint8_t)sp;
    result->status = (uint8_t)status;
    return 1;
}

#endif
